version: "0.1"
user: arsharma111
key: '********'
testSuites: []
pre: [npm install, npx playwright install --with-deps]
preDirectives:
    commands: [npm install, npx playwright install --with-deps]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
jobLabel:
    - playwright-VanillaJS
    - win
    - autosplit
runson: win
autosplit: true
concurrency: 2
testDiscovery:
    autosubset: true
    command: grep -lr '@RegressionTests' tests
    mode: dynamic
    type: raw
testRunnerCommand: npx playwright test
globalTimeout: 20
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 10
testSuiteStep: 5
cacheDirectories:
    - node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
retryOnFailure: true
maxRetries: 1
jobID: 4e2bafc6-e3aa-430f-9954-de0cf657f844
codeDirectory: playwright-lambdatest
report: true
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
        otherApps: []
        customData: {}
        smartUI: null
        darkMode: false
        testRemarks: false
        autoGrantPermissions: false
        networkLogsOptions:
            captureContent: false
            excludeHosts: []
            includeHosts: []
        enableResultBundle: false
        enableBluetooth: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
triggerSource: CLI
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: null
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: 01K9M3966PBZ6FGP3TK502HXEW
    name: unique project name
    type: custom
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig:
    vm: []
    storage:
        region: ""
        enabled: false
        name: ""
        platform: azure
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
globalPre:
    mode: ""
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
    cache: false
    yamlPath: null
    type: ""
    location: ""
globalPost:
    mode: ""
    commands: []
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
slackChannel: ""
whiteLabelProductTag: ""
sprofilePath: ""
ltOptions: {}
